baseURL = "http://example.com/"
languageCode = "en-us"
title = "Elena Miu"
theme = "minimal"
#disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
enableEmoji=true

[params]
    author = "Elena Miu"
    description = "Postdoctoral Research Associate at Aarhus University"
    profilePic = "images/miu_portrait2019.png"
    # profilePic = "img/miu_headshot.jpg"
    githubUsername = "elenamiu"
    accent = "#C93416"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/cv/"
    name = "CV"
    weight = 3

# [[menu.main]]
#     url = "/post/"
#     name = "Posts"
#     weight = 3


# [[menu.main]]
#     url = "/project/"
#     name = "Projects"
#     weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:elena.miu@cas.au.dk"
    name = "fas fa-envelope"
    weight = 1


# [[menu.icon]]
#     url = "https://github.com/elenamiu/"
#     name = "fab fa-github"
#     weight = 2

# [[menu.icon]]
#     url = "https://bsky.app/profile/drelenamiu.bsky.social"
#     name = "fab fa-twitter"
#     weight = 3

# [[menu.icon]]
#     url = "https://www.linkedin.com/in/username/"
#     name = "fab fa-linkedin"
#     weight = 4

# [[menu.icon]]
#     url = "https://www.stackoverflow.com/username/"
#     name = "fab fa-stack-overflow"
#     weight = 5
